name: gamersland
services:
  gamersland_front:
    container_name: gamersland_front
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL_LOCAL=http://localhost:3000
    networks:
      - cloudflared 

networks: 
  cloudflared:
    driver: bridge
    external: true
    