name: gamersland_react
services:
  client_react:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL_LOCAL=http://localhost:3005
    networks:
      - gamersland 

networks: 
  gamersland:
    driver: bridge
    external: true
    